services:
  backend:
    image: web-programming-lab-2
    build:
      context: ./backend
      dockerfile: ./ web-programming-lab-2/Dockerfile
    env_file:
      - backend/.env
    environment:
      - DB_HOST=postgres-db
    networks:
      - lab-network
    ports:
      - "8080:8080"
      - "8081:8081"
      
  frontend:
    image: web-programming-lab-2-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NUXT_PUBLIC_API_BASE=http://localhost:8080/api
    networks:
      - lab-network
    depends_on:
      - backend
    ports:
      - "3000:3000"

networks:
  lab-network:
    external: true