services:
#  web-programming-lab-2:
#    image: web-programming-lab-2
#    build:
#      context: .
#      dockerfile:  web-programming-lab-2/Dockerfile
#    ports:
#      - "8080:8080"
#      - "8081:8081"
#    environment:
#      - DB_HOST=${DB_HOST}
#      - DB_USER=${DB_USER}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - DB_NAME=${DB_NAME}
#      - ConnectionStrings__DefaultConnection=Host=${DB_HOST};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
#    depends_on:
#      - postgres-db
      
  postgres-db:
    image: postgres:latest
    container_name: lab-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  

volumes:
  db-data: